var aplication = angular.module('hotelApp', []);
aplication.controller('hotelController',function($scope){
  $scope.hoteles = [
    {
      name:'Hotel Emperador',
      star01:'star',
      star02:'star',
      star03:'star',
      service01: 'local_bar',
      service02: 'beach_access',
      service03: 'event_available',
      service04: 'local_cafe',
      service05: 'fitness_center',
      service06: 'spa',
      price:'1596',
      img:'assets/img/HotelEmperador.jpg',
      aviso01: 'Precio por noche por habitación',
      aviso02: 'Impuestos y tasas no incluidos',
      pago01: 'Pagá en cuotas',
      pago02: 'Pagá en destino'},
    {
      name:'Petit Palace San Bernardo',
      star01:'star',
      star02:'star',
      star03:'star',
      star04:'star',
      service01: 'beach_access',
      service02: 'person',
      service03: 'event_available',
      service04: 'spa',
      service05: 'wifi',
      service06: 'tv',
      price:'2145',
      img:'assets/img/HotelSanBernardo.jpg',
      aviso01: 'Precio por noche por habitación',
      aviso02: 'Impuestos y tasas no incluidos',
      pago02: 'Pagá en destino'},
    {
      name:'Hotel Nuevo Boston',
      star01:'star',
      star02:'star',
      service01: 'local_bar',
      service02: 'beach_access',
      service03: 'person',
      service04: 'event_available',
      service05: 'local_cafe',
      service06: 'fitness_center',
      price:'861',
      img:'assets/img/HotelNuevoBoston.jpg',
      aviso01: 'Precio por noche por habitación',
      aviso02: 'Impuestos y tasas no incluidos',
      detalle01: 'Precio sin promo',
      sinPromo: 'ARS 1,118',
      pago01: 'Pagá en cuotas'
    }];
});
